---
version: '3'
services:
   dev-maven:
    build: dev/
    volumes:
      - ./data:/usr/local/src
   prod-tomcat:
    build: prod/
    volumes:
      - ./data/hello-1.0.war:/opt/bitnami/tomcat/webapps
