---
version: '3'
services:
   dev-maven:
    build: dev/
    volumes:
      - ./data:/usr/share
   prod-tomcat:
       build: prod/
       ports:
          - "8080:8080"
       volumes:
        - ./data:/usr/local/tomcat/webapps
volumes:
   data:

