---
version: '3'
services:
   dev-maven:
     build: dev/
   prod-tomcat:
     image: tomcat:9.0
     depends_on:
       - dev-maven
     ports:
       - "8080:8080"
     volumes:
       - data:/usr/local/tomcat/webapps
volumes:
  data: